export const category_channels = [
  {
    category: "tools",
    channels: [
      "audio-tools",
      "career-tools",
      "developer-tools",
      "discord-tools",
      "educational-tools",
      "file-tools",
      "facebook-tools",
      "gaming-tools",
      "general-tools",
      "image-tools",
      "internet-tools",
      "reddit-tools",
      "search-tools",
      "system-tools",
      "telegram-tools",
      "text-tools",
      "twitch-tools",
      "twitter-tools",
      "url-tools",
      "video-tools",
      "youtube-tools",
    ],
  },
  {
    category: "miscellaneous",
    channels: [
      "browser-games",
      "cooking",
      "extensions",
      "fonts",
      "fun-sites",
      "health",
      "indexes",
      "maps",
      "media-databases",
      "news",
      "non-english",
      "piracy-discussion",
      "request-media",
      "subtitles",
    ],
  },
  {
    category: "reading",
    channels: [
      "audiobooks",
      "comics",
      "ebook-readers",
      "educational",
      "general",
      "light-novels",
      "manga",
      "magazines",
      "religion-esoteric",
      "newspapers",
    ],
  },
  {
    category: "android_ios",
    channels: [
      "android-adblocking",
      "android-audio",
      "android-emulators",
      "android-general",
      "android-privacy",
      "android-reading",
      "android-torrenting",
      "android-video",
      "ios-adblocking",
      "ios-audio",
      "ios-general",
      "ios-jailbreaking",
      "ios-privacy",
      "ios-torrenting",
      "ios-reading",
      "ios-video",
    ],
  },
  {
    category: "downloading",
    channels: [
      "anime",
      "arcade-retro",
      "educational",
      "emulators-roms",
      "games",
      "general",
      "movies-tv",
      "music",
      "software",
      "usenet",
    ],
  },
  {
    category: "torrenting",
    channels: [
      "anime",
      "educational",
      "games",
      "general",
      "movies-tv",
      "music",
      "torrent-clients",
    ],
  },
  {
    category: "linux_macos",
    channels: [
      "linux-adblock-privacy",
      "linux-gaming",
      "linux-general",
      "linux-software",
      "mac-adblock-privacy",
      "mac-gaming",
      "mac-general",
      "mac-software",
    ],
  },
  {
    category: "streaming",
    channels: [
      "ambient-relaxation",
      "anime",
      "educational",
      "movies-tv",
      "live-tv",
      "podcasts-radio",
      "music",
      "sports",
    ],
  },
  {
    category: "adblock_privacy",
    channels: ["adblocking", "antivirus", "dns", "privacy", "proxies", "vpn"],
  },
];
export const resources = [
  {
    link: "/links/adblock-vpn-privacy",
    emoji: "📛",
    title: "Adblock, Privacy, Antivirus",
  },
  {
    link: "/links/video",
    emoji: "📺",
    title: "Movies, TV, Anime, Sports",
  },
  {
    link: "/links/audio",
    emoji: "🎵",
    title: " Music, Podcasts, Radio ",
  },
  { link: "/links/games", emoji: "🎮", title: "Gaming, Emulation" },
  {
    link: "/links/reading",
    emoji: "📗",
    title: "Books, Comics, Manga",
  },
  { link: "/links/download", emoji: "💾", title: "Downloading" },
  { link: "/links/torrent", emoji: "🌀", title: "Torrenting" },
  { link: "/links/edu", emoji: "🧠", title: "Educational" },
  { link: "/links/tools-misc", emoji: "🔧", title: "Tools" },
  { link: "/links/misc", emoji: "📂", title: "Miscellaneous" },
  { link: "/links/android", emoji: "📱", title: "Android, iOS" },
  { link: "/links/linux", emoji: "🐧", title: "Linux, MacOS" },
  { link: "/links/storage", emoji: "📦", title: "Storage" },
  { link: "/links/non-eng", emoji: "🌍", title: "Non English" },
  { link: "/links/base64", emoji: "🔗", title: "Base 64" },
];

export const MARKDOWN_RESOURCES = [
  {
    title: "Home",
    urlEnding: "Home",
    emoji: "👋",
  },
  {
    title: "Adblock, Privacy",
    urlEnding: "AdblockVPNGuide",
    emoji: "📛",
  },
  {
    title: "AI Tools",
    urlEnding: "AI",
    emoji: "🤖",
  },
  {
    title: "Android, iOS",
    urlEnding: "Android-iOSGuide",
    emoji: "📱",
  },
  {
    title: "Beginners Guide",
    urlEnding: "Beginners-Guide",
    emoji: "🏴‍☠️",
  },
  {
    title: "Books, Comics, Manga",
    urlEnding: "ReadingPiracyGuide",
    emoji: "📗",
  },

  {
    title: "Developer Tools",
    urlEnding: "DEVTools",
    emoji: "👨‍💻",
  },
  {
    title: "Downloading",
    urlEnding: "DownloadPiracyGuide",
    emoji: "💾",
  },
  {
    title: "Educational",
    urlEnding: "EDUPiracyGuide",
    emoji: "🧠",
  },

  {
    title: "Gaming, Emulation",
    urlEnding: "GamingPiracyGuide",
    emoji: "🎮",
  },
  {
    title: "Image Tools",
    urlEnding: "img-tools",
    emoji: "🖼️",
  },
  {
    title: "Linux, MacOS",
    urlEnding: "LinuxGuide",
    emoji: "🐧",
  },
  {
    title: "Miscellaneous",
    urlEnding: "MISCGuide",
    emoji: "📂",
  },
  {
    title: "Movies, TV, Anime, Sports",
    urlEnding: "VideoPiracyGuide",
    emoji: "📺",
  },
  {
    title: "Music, Podcasts, Radio",
    urlEnding: "AudioPiracyGuide",
    emoji: "🎵",
  },

  {
    title: "Non-English",
    urlEnding: "Non-English",
    emoji: "🌍",
  },

  {
    title: "Storage",
    urlEnding: "STORAGE",
    emoji: "📦",
  },
  {
    title: "Tools",
    urlEnding: "TOOLSGuide",
    emoji: "🔧",
  },
  {
    title: "Torrenting",
    urlEnding: "TorrentPiracyGuide",
    emoji: "🌀",
  },
  {
    title: "NSFW",
    urlEnding: "NSFWPiracy",
    emoji: "🔞",
  },
];

// const generateTitleMapFromRedditToGithub = () => {
//   // ps: update resoruces array, its outdated
//   const mapping = {};
//   MARKDOWN_RESOURCES.forEach((item) => {
//     const matchingResource = resources.find(
//       (resource) => resource.emoji === item.emoji
//     );
//     if (!matchingResource) {
//       console.log("missing", item);
//       return;
//     }

//     mapping[matchingResource.link.split("/").at(-1)] =
//       item.urlEnding.toLowerCase();
//     return;
//   });

//   console.log(mapping);
// };

// CATEGORY NAMES DONT MATCH. NEED TO FIX
const CATEGORY_SUBCATEGORY_MAPPING = [
  {
    category: "adblock",
    subcategory: {
      Adblocking: [
        "Adblocking Extensions",
        "DNS Adblocking",
        "Linux Adblocking",
        "Mac Adblocking",
        "Android Adblocking",
        "iOS Adblocking",
      ],
      Antivirus: [],
      Privacy: [
        "Privacy Tools",
        "Privacy Extensions",
        "Browser Tools",
        "Search Engines",
        "Email Services",
        "Linux Privacy",
        "Mac Privacy",
        "Android Privacy",
        "iOS Privacy",
      ],
      VPN: [],
      Proxy: ["Proxy Apps", "Proxy Sites"],
    },
  },
  {
    category: "ai tools",
    subcategory: {
      "AI Chatbots": ["ChatGPT Tools", "ChatGPT Prompts"],
      "AI Indexes": [],
      "Text Generators": [
        "Text Rephrashing",
        "Summary Generators",
        "Grammar Check",
        "Text to Speech",
        "Plagiarism Detection",
        "AI Text Detection",
      ],
      "Image Generators": [
        "Image Restoration",
        "Image Colorization",
        "Image Upscaling",
        "Background Removal",
        "Generator Guides",
      ],
      "Audio Generators": ["Voice Change / Clone"],
      "Machine Learning": [],
    },
  },
  {
    category: "androud ios",
    subcategory: {
      "Android Adblocking": [],
      "Android Privacy": [],
      "Android APKs": [],
      "Android Emulators": [],
      "Android Tools": [],
      "Android Gaming": [],
      "Android Torrenting": [],
      "Android Reading": [],
      "Android Audio": ["Android Podcasts / Radio", "Android Relaxation"],
      "Android Streaming": ["Android Anime", "Android Live TV"],
      "iOS Jailbreaking": [],
      "iOS Adblocking": [],
      "iOS Privacy": [],
      "iOS Apps": [],
      "iOS Tools": [],
      "iOS Audio": ["iOS Podcasts / Radio", "iOS Relaxation"],
      "iOS Streaming": ["iOS Anime", "iOS Live TV"],
      "iOS Torrenting": [],
      "iOS Reading": [],
    },
  },

  {
    category: "books comics",
    subcategory: {
      "Audiobook Sites": [],
      "Reading Sites": [
        "PDF Search",
        "Classic Sites",
        "Religion / Esoterica",
        "Special Interest",
      ],
      "Educational Sites": [
        "History Sites",
        "Programming Sites",
        "Documents / Articles",
        "Manual Sites",
        "Reference Sites",
      ],
      "Visual Media Sites": [
        "Comic Sites",
        "Manga Sites",
        "Manhua / Manhwa",
        "Light Novel Sites",
        "Magazine Sites",
        "Newspaper Sites",
      ],
      "Tracking / Discovery": [],
      "Ebook Readers": [],
      "Helpful Sites / Apps": [],
    },
  },

  {
    category: "devtools",
    subcategory: {
      "Learning / Cheat Sheets": [
        "Web Development",
        "Game Development",
        "App Development",
        "Data Structures",
        "Data Science",
        "Python",
        "C / C++",
        "Cybersecurity",
        "Linux / CLI",
        "Git",
        "UI / UX",
      ],
      "Developer Tools": [
        "Web Dev Tools",
        "Software Dev Tools",
        "App Dev Tools",
        "Game Dev Tools",
        "Git Tools",
        "CLI Tools",
        "Color Schemes",
        "Machine Learning",
      ],
      "Programming / Coding": [
        "IDEs / Code Editors",
        "Cloud IDEs / Collab",
        "Markup Tools",
        "API Tools",
      ],
    },
  },

  {
    category: "dowload",
    subcategory: {
      "Download Directories": [],
      "Download Sites": [
        "Search Sites",
        "Video Sites",
        "Anime Sites",
        "Educational Sites",
        "Game Sites",
        "Audio Sites",
      ],
      "Software Sites": ["Freeware Sites", "Linux Software", "Mac Software"],
      "File Sharing Apps": [],
      Usenet: ["Indexers", "Providers", "Downloaders"],
      "File Leeches": [],
      "File Tools": [],
    },
  },
  {
    category: "educational",
    subcategory: {
      Streaming: ["Courses", "Documentaries"],
      Downloading: ["Courses", "Documentaries"],
      Torrenting: ["Courses", "Documentaries"],
      Reading: [
        "History Books",
        "Programming Books",
        "Documents / Articles",
        "Manual Sites",
        "Reference Sites",
      ],
      Games: [],
      Math: [],
      Physics: [],
      Biology: [],
      Chemistry: [],
      "World Data": [],
      History: [],
      Space: [],
      Art: [],
      "Virtual Tours": [],
      Development: [],
      "Language Learning": [
        "Multi-Language",
        "English",
        "Japanese",
        "Korean",
        "Chinese",
        "European",
        "South Asian",
        "Other Languages",
      ],
      "Music Learning": [],
      "Educational Tools": [],
    },
  },
  {
    category: "gaming",
    subcategory: {
      "Download Games": [
        "Game Repacks",
        "DLC Unlockers",
        "Single Games",
        " Linux Games",
        " Mac Games",
        " Android Games",
      ],
      "Emulation / ROMs": [
        "Emulators",
        "ROM Sites",
        "Browser Emulators",
        "Arcade / Retro",
      ],
      "Browser Games": [
        "Multiplayer",
        "Board / Card / Dice",
        "Puzzle Games",
        "Incremental / Idle",
        "Guessing Games",
        "Flash Games",
      ],
      Homebrew: [],
      "Game Mods": [],
      "Tracking / Discovery": [],
      "Gaming Tools": [
        "Optimization Tools",
        "Multiplayer Tools",
        "Steam / Epic",
        "GTA Tools",
        "Minecraft Tools",
        "Terraria Tools",
        "Tabletop Tools",
        "Git Gud",
      ],
    },
  },
  {
    category: "image tools",
    subcategory: {
      "Image Editing": ["Resize / Compress", "Restoration"],
      "Image Generation": [
        "GIF Tools",
        " Meme Makers",
        "Painting / Drawing",
        "Pixel Art",
      ],
      "Download Images": ["Wallpapers", "3D Models"],
      "Image Tools": [
        " Hosting / Viewing",
        "Screenshot Tools",
        " Image Converters",
        "Instagram Tools",
        "Photo Forensics",
      ],
      "Art Education": [],
    },
  },
  {
    category: "linux macos",
    subcategory: {
      "Linux Tools / Apps": [],
      "Linux Adblock / Privacy": [],
      "Linux Software": [],
      "Linux Gaming": [],
      "Mac Tools / Apps": [],
      "Mac Adblock / Privacy": [],
      "Mac Software": [],
      "Mac Gaming": [],
    },
  },
  {
    category: "misc",
    subcategory: {
      Indexes: [],
      "Piracy Discussion": [],
      "Free Stuff": [],
      "Fun Sites": [],
      News: [],
      Food: [],
      Gardening: [],
      " Health": [],
      Maps: [],
      " Fonts": [],
      Extensions: [
        "Multi Browser",
        "Firefox",
        "Chrome",
        "Safari",
        "Userscripts",
      ],
      Shopping: ["Electronics", "Games", "Price Tracking"],
    },
  },
  {
    category: "streaming",
    subcategory: {
      "Streaming Sites": [
        "Dedicated Hosts",
        "Multi Hosts",
        "Video Hosts",
        "Specialty Streaming",
        "Educational Streaming",
      ],
      "TV Streaming": [
        "Anime Streaming",
        "Cartoon Streaming",
        "Drama Streaming",
        "Sports Streaming",
        "Live TV / Sports",
        "Smart TV / Firestick",
      ],
      "Android Streaming": [],
      "iOS Streaming": [],
      "Download Sites": [
        "Drives / Directories",
        "Anime Downloading",
        "Educational Downloading",
      ],
      "Torrent Apps": [],
      "Torrent Sites": ["Anime Torrenting", "Educational Torrenting"],
      "Tracking / Discovery": [],
      Subtitles: [],
      "Helpful Sites / Tools": [],
    },
  },
  {
    category: "music podcast",
    subcategory: {
      "Audio Streaming": [
        "Streaming Apps",
        "Streaming Sites",
        "Podcasts / Radio",
        "Ambient / Relaxation",
      ],
      "Audio Downloading": ["Download Apps", "Download Sites"],
      "Audio Torrenting": [],
      "Android Audio": [],
      "iOS Audio": [],
      "Tracking / Discovery": [],
      "Audio Tools": [],
    },
  },
  {
    category: "tools",
    subcategory: {
      "General Tools": [
        "Text Tools",
        "Image Tools",
        "Video Tools",
        "Audio Tools",
        "Gaming Tools",
        "Educational Tools",
        "Career Tools",
        "AI Tools",
        "Developer Tools",
      ],
      "Internet Tools": [
        "Browsers",
        "Search Tools",
        "URL Tools",
        "Reddit Tools",
        "Discord Tools",
        "Telegram Tools",
        "YouTube Tools",
        "Twitch Tools",
        "Twitter Tools",
        "4chan Tools",
        "Facebook Tools",
        "Instagram Tools",
      ],
      "System Tools": [
        "Optimization",
        "Customization",
        "Tweaking",
        "File Tools",
        "Virtual Machines",
        "Terminal / CLI",
        "Linux Tools",
        "Mac Tools",
        "Android Tools",
        "iOS Tools",
      ],
    },
  },
  {
    category: "torrenting",
    subcategory: {
      "VPN Guide": [],
      "Torrent Clients": [
        "Remote Torrenting",
        "Android Clients",
        "iOS Clients",
      ],
      "Torrent Sites": [
        "Aggregators",
        "Video Sites",
        "Anime Sites",
        "Educational Sites",
        "Game Sites",
        "Audio Sites",
      ],
      "Tracker Invites": [],
      "Helpful Sites / Apps": [],
    },
  },
  {
    category: "storage",
    subcategory: {
      "3D Modeling Apps": [],
      "3D Models": [],
      "3DS ROMs": [],
      "4chan Archives": [],
      "Adblock Defenders": [],
      "Alternative Search Engines": [],
      "Alternative Software / App Sites": [],
      "Ambient Rain Sounds": [],
      "Android Audio Players": [],
      "Android Browsers": [],
      "Android File Explorers": [],
      "Android Note Apps": [],
      "Android Operating Systems": [],
      "Android TV IPTV Players": [],
      "Anime Download Apps": [],
      "Anonymous Image Boards": [],
      Antivirus: [],
      "App Launchers": [],
      "Audio Converters": [],
      "Audio Editors": [],
      "Audio Plugins": [],
      "Audio Servers": [],
      "Audio Synthesizers": [],
      "Automation Tools": [],
      "ASCII Art Creators": [],
      "Background Removers": [],
      "BetterDiscord Tools": [],
      "Blogging Platforms": [],
      "Browser eBook Readers": [],
      "Browser Games": [],
      "Browser Startpages": [],
      "Bookmark Managers": [],
      "Bulk File Renamers": [],
      "Calculator Sites": [],
      Calendars: [],
      "Calibre Libraries": [],
      "Calibre Tools": [],
      "Character / Word Counters": [],
      "Clipboard Managers": [],
      "Code Editors": [],
      "Coding Tutorials": [],
      "Color Palette Generators": [],
      "Color Pickers": [],
      "Collaboration Platforms": [],
      "Cooking YouTube Channels": [],
      "Copy Google Drives": [],
      "Command Line Shells": [],
      "Compression Programs": [],
      "Covers / Posters": [],
      "Customizable New Tab Page": [],
      "Custom Rich Discord Presence": [],
      "Data Visualization Tools": [],
      "Decentralized Social Networks": [],
      "Design Resources": [],
      "Developer Tools": [],
      "Dev YouTube Channels": [],
      "Discord Embed Generators": [],
      "Discord Server / Bot Lists": [],
      "Disk Usage Analyzers": [],
      "DNS Filters": [],
      "Domain Info Tools": [],
      "Docker Tools": [],
      "DOS Games": [],
      "Down Site Checkers": [],
      "Drive Formatting / File Deletion": [],
      "Email Clients": [],
      "Email Forwarding": [],
      "Email Sites": [],
      "Encode / Decode URLs": [],
      "Encrypted Android Messengers": [],
      "Encrypted Email Services": [],
      "Encrypted Messengers": [],
      "Encrypted XMPP Servers": [],
      "External Subs Player": [],
      "FFmpeg Tools": [],
      "Flash Player Tools": [],
      "F2P Games": [],
      "Fun Indexes": [],
      "Free DNS Servers": [],
      "Free VPN Configs": [],
      "Free Webhosting Sites": [],
      "File Backup Tools": [],
      "File Conversion Tools": [],
      "File Download Managers": [],
      "File Encryption Tools": [],
      "File Recovery Tools": [],
      "File Sharing Tools": [],
      "Nutrition / Ingredients": [],
      "FMovies Clones": [],
      "Game Download CSE": [],
      "Game Engines": [],
      "Game Guides": [],
      "Game Libraries / Launcher": [],
      "Game Mods": [],
      "GDrive File Sharing": [],
      "Git Projects": [],
      "Google Drive Search": [],
      "Google Piracy Discussion Groups": [],
      "Grammar Check": [],
      "Graph / Diagram Creators": [],
      "Graphic Design Tools": [],
      "Health News": [],
      "Hide YouTube Shorts": [],
      "Icon Download Sites": [],
      "Image Colorization": [],
      "Image Design Resources": [],
      "Image Download Extensions": [],
      "Image Editing": [],
      "Image Hosts": [],
      "Image Upscalers": [],
      "Image to Text": [],
      "Image Viewers": [],
      "Interactive Math Sites": [],
      "Internet Speed Test": [],
      "IP Checkers": [],
      "IP / DNS Leak Tests": [],
      "IP / Network Tools": [],
      "IPTV Playlists": [],
      "IPTV Tools": [],
      "IRC Book Sites": [],
      "Jigsaw Puzzles": [],
      "Keyboard Testers": [],
      "Kodi Tools": [],
      "LibGen  Mirrors": [],
      "LibGen Tools": [],
      "Link Protectors": [],
      "Linux Distros": [],
      "Linux Themes": [],
      "Live Webcams": [],
      "M3U Players": [],
      "M4UFree Clones": [],
      "Magic / Esoteric Telegram Ebooks": [],
      "Manga Downloaders": [],
      "Manga Readers": [],
      "Manually Scrape Sites": [],
      "Media File Data Automation": [],
      "Media Servers": [],
      "Mind Mapping": [],
      "Minecraft Mods": [],
      "Minecraft Optimization Mods": [],
      "Minecraft Servers": [],
      "Mouse Gestures": [],
      "Modded APKs": [],
      "Modded Minecraft Launchers": [],
      "Multi Image Tool Sites": [],
      "Multiplayer Fixes": [],
      Multireddits: [],
      "Multi Site Cloud Storage Managers": [],
      "Multi Site Video Downloaders": [],
      "Multi Text Tool Sites": [],
      "Multi Tool Sites": [],
      "Music Libraries / Players": [],
      "Name & Identity Generators": [],
      "News Feed Aggregators": [],
      "Note Taking / To Do Apps": [],
      "Office Suites": [],
      "Open Directory Search String Builder": [],
      "Open Source APKs": [],
      "Open Source Intelligence Indexes": [],
      Origami: [],
      "OS Emulators": [],
      "Password Managers": [],
      "Password Data Breach Check": [],
      Pastebins: [],
      "PDF Editors / Toolkits": [],
      "Periodic Tables": [],
      "Persian Video Download": [],
      "Personal Link Homepages": [],
      "Plagiarism Detection": [],
      "Piracy Site Proxies": [],
      "Poll Sites": [],
      "Popup Blocker Links": [],
      "Portable Apps": [],
      "Portuguese Browser Games": [],
      "Portuguese Bibles": [],
      "Portuguese Dictionaries / Thesaurus": [],
      "Portuguese Grammar Tips & Lessons": [],
      "Portuguese Recipes": [],
      "Presentation Tools": [],
      "Proxy Lists": [],
      "Privacy Based Browsers": [],
      "Privacy Guides": [],
      "Privacy Hardened Firefox": [],
      "Privacy Tools": [],
      "qBitorrent Tools": [],
      "QR Code Generators": [],
      "Radio Streaming Sites": [],
      "Random Image Sites": [],
      "Random Sites": [],
      "RARBG Mirrors": [],
      "Read Paywalled Articles": [],
      "Reddit Alternatives": [],
      "Reddit Desktop Apps": [],
      "Reddit Frontends": [],
      "Reddit Streams": [],
      "Remote Desktop Clients": [],
      "Remove Vocals": [],
      "Resume Makers": [],
      "Reverse Image Search": [],
      "Royalty Free Music": [],
      "RSS Feed Readers": [],
      "Satellite & Street View Maps": [],
      "Scan Files": [],
      "Screen Recorders": [],
      "Scene Release Trackers": [],
      "Searx Instances": [],
      "Send Anonymous Emails": [],
      "SEO Tools": [],
      "SFlix Clones": [],
      "SFX / Loops": [],
      "Sheet Music Sites": [],
      "Similar Site Indexes": [],
      "Site Analytics": [],
      "Site Legitimacy Check": [],
      "SockShare Clones": [],
      "Song Identification": [],
      "Skip Redirect": [],
      "SMS Verification Sites": [],
      "Soundcloud Downloaders": [],
      "Spanish Anime Telegram": [],
      "Sports Streaming": [],
      "Sports Streaming Subs": [],
      "Spotify Downloaders": [],
      "Spotify Tools": [],
      "Steam Workshop Downloaders": [],
      "Streaming Site CSE": [],
      "Stock Photo Sites": [],
      "Stock Video Sites": [],
      "Subreddit Discovery": [],
      "Summary Generator": [],
      "Sun / Moon Position": [],
      "Switch Homebrew Discord Servers": [],
      "Switch Roms": [],
      "System Monitors": [],
      "Tab Managers": [],
      "TeamDrive Generators": [],
      "Tech News": [],
      "Temp Email Sites": [],
      "Telegram Anime Downloads": [],
      "Telegram Audiobook Downloads": [],
      "Telegram Audio Download": [],
      "Telegram Audio Download Bots": [],
      "Telegram Bots": [],
      "Telegram Deezer Bots": [],
      "Telegram File Tools": [],
      "Telegram eBook Download": [],
      "Telegram Video Download": [],
      "Text Adventures": [],
      "Text / Code Collaboration": [],
      "Text Editors": [],
      "Text Rephrashing": [],
      "Text to Speech": [],
      "TikTok Video Downloaders": [],
      "Tor Search Engines": [],
      "Tor Tools": [],
      "Torrent to GDrive": [],
      "Tracker Lists": [],
      "Translation Sites": [],
      "Typing Lessons": [],
      "Twitch Adblockers": [],
      "uBlock Filters": [],
      "Udemy Coupons": [],
      "Unicode Font Generators": [],
      "Untouched APKs": [],
      "URL Unshorteners": [],
      "Userscript Managers": [],
      "VFX Sites": [],
      "Video Chat": [],
      "Video Converters": [],
      "Video Editors": [],
      "Video Hosting Sites": [],
      "Video Players": [],
      "Video Stream Sync": [],
      "Vim Tools": [],
      "VSCode Tools": [],
      Wallpapers: [],
      "WebFont Changer": [],
      "Website Creators": [],
      "Web Scraping / Archiving Tools": [],
      "Windows 10 Antispy Tools": [],
      "Windows 10 Debloater": [],
      "Windows Activation": [],
      "Windows File Explorers": [],
      "Windows ISO": [],
      "Window Tiling Programs": [],
      "Wordpress Themes": [],
      "Worldwide News Sites Index": [],
      "Youtube Android Apps": [],
      "YouTube Frontends": [],
      "YouTube Movies": [],
      "YouTube Music Players": [],
      "YouTube to MP3": [],
      "YouTube Video Downloaders": [],
      "YT-DL Tools": [],
    },
  },
  {
    category: "non-english",
    subcategory: {
      Arabic: ["Downloading", "Torrenting", "Streaming", "Reading"],
      Bangla: ["Reading", "Streaming"],
      Bulgarian: ["Downloading", "Torrenting"],
      Burmese: ["Streaming", "Downloading"],
      Chinese: ["Downloading", "Torrenting", "Streaming", "Reading"],
      Czech: ["Downloading", "Torrenting", "Streaming"],
      Danish: ["Streaming"],
      Filipino: ["Streaming"],
      Finnish: ["Streaming", "Reading"],
      French: ["Downloading", "Torrenting", "Streaming", "Reading"],
      German: ["Downloading", "Streaming", "Reading"],
      Georgian: ["Downloading", "Streaming"],
      Greek: ["Streaming"],
      Hebrew: ["Streaming"],
      Hindi: ["Downloading", "Torrenting", "Streaming", "Reading"],
      Hungarian: ["Streaming"],
      Icelandic: ["Torrenting"],
      Indonesian: ["Downloading", "Streaming", "Reading"],
      Italian: ["Downloading", "Torrenting", "Streaming", "Reading"],
      Japanese: ["Downloading", "Torrenting", "Streaming", "Reading"],
      Korean: ["Downloading", "Torrenting", "Streaming", "Reading"],
      Malay: ["Downloading", "Reading"],
      Norwegian: ["Streaming", "Reading"],
      Persian: ["Downloading", "Torrenting", "Streaming", "Reading"],
      Polish: ["Downloading", "Torrenting", "Streaming", "Reading"],
      Portuguese: ["Downloading", "Torrenting", "Streaming", "Reading"],
      Romanian: ["Streaming", "Download"],
      Russian: ["Downloading", "Torrenting", "Streaming", "Reading"],
      Slovak: ["Streaming"],
      Spanish: ["Downloading", "Torrenting", "Streaming", "Reading"],
      Swedish: ["Streaming"],
      Tamil: ["Streaming", "Downloading"],
      Telugu: ["Downloading"],
      Thai: ["Streaming", "Reading"],
      Turkish: ["Downloading", "Streaming", "Reading"],
      Ukrainian: ["Torrenting", "Reading"],
      "►Uzbek": ["Downloading", "Streaming", "Reading"],
      Vietnamese: ["Downloading", "Torrenting", "Streaming", "Reading"],
      "Multi Indian Languages": [],
      "Other Languages": [],
    },
  },
];
