"use client";

import Navbar from "@/components/Navbar";
import { SpotlightProvider } from "@/components/Spotlight";
import { fontSans } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import { MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { DefaultSeo } from "next-seo";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      {/* <QueryClientProvider client={queryClient}>
          <SpotlightProvider>
            <DefaultSeo
              title="FreeMediaHeckYeah"
              description="The Largest collection of Free stuff on the Internet! | FMHY"
              openGraph={{
                type: "website",
                locale: "en_US",
                url: "FMHY",
                // url: "https://www.fmhy.net/",
                siteName: "FreeMediaHeckYeah",
                images: [{ url: "https://fmhy.net/assets/logo.png" }],
              }}
              // canonical="https://www.fmhy.net/"
            /> */}

      <body>
        <MantineProvider
          theme={{
            colorScheme: "dark",
          }}
        >
          <div
            // className="flex flex-col h-screen gap-2"
            className={cn(
              "antialiased flex flex-col h-screen gap-2 max-w-[100vw] ",
              fontSans.className
            )}
          >
            <Notifications />
            <Navbar />
            <div className="px-2 flex-1 flex overflow-y-scroll">{children}</div>
          </div>
        </MantineProvider>
      </body>
      {/* </SpotlightProvider>
          <ReactQueryDevtools />
        </QueryClientProvider> */}
    </html>
  );
}
